// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5k-9TuxRnEq66ipezf-Ho853FBVb1UZ4',
    appId: '1:309809242149:web:396c52f82a5df5eb0a1fcc',
    messagingSenderId: '309809242149',
    projectId: 'shen-yemen',
    authDomain: 'shen-yemen.firebaseapp.com',
    storageBucket: 'shen-yemen.firebasestorage.app',
    measurementId: 'G-WL0S9DKMFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Zd1f_KamKyZoDJXz0CQ5EGt0vRXjTm4',
    appId: '1:309809242149:android:945f471b67d362a00a1fcc',
    messagingSenderId: '309809242149',
    projectId: 'shen-yemen',
    storageBucket: 'shen-yemen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ5WpFv9TexJmVPxsBBebs23re1KTdO6I',
    appId: '1:309809242149:ios:aaffbc6b6fc097830a1fcc',
    messagingSenderId: '309809242149',
    projectId: 'shen-yemen',
    storageBucket: 'shen-yemen.firebasestorage.app',
    iosBundleId: 'com.example.google',
  );
}
