// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8JtFF1VfJICW10rQfn_ZR6-B6mgr3Oo4',
    appId: '1:598653212605:web:cf5bf3eaefaaff9b5f24d4',
    messagingSenderId: '598653212605',
    projectId: 'seeshein-3b3dd',
    authDomain: 'seeshein-3b3dd.firebaseapp.com',
    storageBucket: 'seeshein-3b3dd.firebasestorage.app',
    measurementId: 'G-68BDRFNSLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzCGWVHZVxsuEef-m3QXYSs6neC9-q_o4',
    appId: '1:598653212605:android:79cf0a2cc3651f465f24d4',
    messagingSenderId: '598653212605',
    projectId: 'seeshein-3b3dd',
    storageBucket: 'seeshein-3b3dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcPdUn8O6XHA1xglKQytoImgz64mE7G24',
    appId: '1:598653212605:ios:4d1e95c0d590d51d5f24d4',
    messagingSenderId: '598653212605',
    projectId: 'seeshein-3b3dd',
    storageBucket: 'seeshein-3b3dd.firebasestorage.app',
    iosBundleId: 'com.shen.yemen',
  );
}
